// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxtwsbsdelhxxyloqhfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4dHdzYnNkZWxoeHh5bG9xaGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMTk2OTEsImV4cCI6MjA3NDU5NTY5MX0.xxT5xbT9x0pdaUC14WqaLnknbcd4QnS2QNVSQ2hgglE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});